version: '3.4'
services:
  db:
    image: sqlserver-qanostorage:0.0.1
    container_name: SqlServerQANoStorage    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
        - SA_PASSWORD=Admin@123
        - ACCEPT_EULA=Y
        - DATABASE_NAME=test_db_5
        - USERNAME_APPLICATION=application_user
        - PASSWORD_APPLICATION=Pass_word_123
        - TZ=America/Fortaleza
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Admin@123", "-Q", "select 1"] 
      timeout: 1s
      retries: 10