CREATE TABLE TB_CUSTOMER
(
    ID_CUSTOMER INT IDENTITY(1,1),
    NAME VARCHAR(250) NOT NULL
)

INSERT INTO TB_CUSTOMER (NAME) VALUES ('LEANDRO BIANCH DA SILVA')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('SILVA BIANCH DA SILVA')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('BILL GATES')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('STEVE JOBS')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('EDDIE VEDDER')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('DAVID GILMOUR')